---
name: 反馈问题
description: 问题反馈模板
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: 提问题之前，请先确认
      description: "请勾选以下确认项"
      options:
        - label: "已经阅读过Q&A (https://musicfree.catcat.work/qa/mobile.html)"
          required: true
        - label: "要提出的问题与插件功能无关（类似插件搜索结果不全、ip被封禁等请找对应插件作者）"
          required: true
        - label: "不与其他已有issue重复"
          required: true

  - type: textarea
    id: system_info
    attributes:
      label: 系统信息
      description: "请填写以下系统信息"
      placeholder: |
        软件版本：
        系统版本：
        设备型号：
    validations:
      required: true

  - type: textarea
    id: problem_description
    attributes:
      label: 问题描述
      description: "请详细描述问题现象及预期正确行为"
      placeholder: "例如：当执行XX操作时，出现XX现象，预期应该XX..."
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: 复现步骤
      description: "请按顺序描述复现步骤"
      placeholder: |
        1. 打开应用
        2. 点击XX按钮
        3. ...
    validations:
      required: true

  - type: textarea
    id: screenshots_logs
    attributes:
      label: 截图 & 日志
      description: "请粘贴截图链接或错误日志（可拖放文件直接上传截图）"
      placeholder: "错误日志示例：\n[2023-01-01 12:00] ERROR: xxxx"
    validations:
      required: false
