name: 构建APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24  # 这里改成 24，彻底解决弃用警告
          cache: 'yarn'

      - name: 安装项目依赖
        run: yarn install

      - name: 构建APK
        run: yarn run build-app

      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: XlingMusic-APK
          path: release/
