name: 自动构建APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 安装 Flutter 环境
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: stable

      - name: 检查环境
        run: flutter doctor -v

      - name: 安装项目依赖
        run: flutter pub get

      - name: 构建正式版APK
        run: flutter build apk --release

      - name: 上传APK文件
        uses: actions/upload-artifact@v4
        with:
          name: my-apk
          path: build/app/outputs/flutter-apk/app-release.apk
