name: 构建APK
on:
  workflow_dispatch:

# 按官方要求：全局强制使用 Node24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 安装项目依赖
        run: yarn install

      - name: 构建APK
        run: yarn run build-app

      - name: 上传APK
        uses: actions/upload-artifact@v4
        with:
          name: XlingMusic-APK
          path: release/
