name: Build APK

on:
  push:
    branches: master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Android APK
        run: yarn build:android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: XlingMusic-APK
          path: ./release/
