name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Android APK
        run: npm run build-android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: XlingMusic-APK
          path: release/*.apk
